---
settings:
  name: Release Notes
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Note sulla versione della console NetApp
    url: "/index.html"
  - title: Modifiche recenti
    url: "/whats-new.html"
  - title: Indice delle note di rilascio
    url: "/release-notes-index.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: NetApp Console
  repo: console-family
