---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Scopri le modifiche più recenti apportate alle funzionalità e ai servizi dati che fanno parte della NetApp Console. 
---
= Modifiche recenti nella NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le modifiche più recenti apportate alle funzionalità e ai servizi dati che fanno parte della NetApp Console.  Per una cronologia completa delle versioni, vai alink:release-notes-index.html["set completo di note di rilascio"] per ogni singolo servizio.



== Caratteristiche amministrative

Questa sezione descrive le nuove funzionalità relative alle funzionalità di amministrazione NetApp Console : organizzazioni, identificazione e accesso, agenti della console, credenziali del provider cloud e altro ancora.



== Avvisi



== Amazon FSx per ONTAP



=== 06 ottobre 2025



==== BlueXP è ora NetApp Console

NetApp Console, basata sulle fondamenta BlueXP migliorate e ristrutturate, offre una gestione centralizzata dello storage NetApp e NetApp Data Services in ambienti on-premise e cloud di livello aziendale, offrendo informazioni in tempo reale, flussi di lavoro più rapidi e un'amministrazione semplificata, il tutto in modo altamente sicuro e conforme.

Per i dettagli su cosa è cambiato, vederelink:https://docs.netapp.com/us-en/console-relnotes/index.html["Note sulla versione NetApp Console ."^]



=== 03 agosto 2025



==== Miglioramenti alla scheda Relazioni di replicazione

Abbiamo aggiunto diverse nuove colonne alla tabella delle relazioni di replicazione per fornirti maggiori informazioni sulle relazioni di replicazione nella scheda *Relazioni di replicazione*. La tabella ora include le seguenti colonne:

* Politica SnapMirror
* File system sorgente
* File system di destinazione
* Stato della relazione
* Ultimo orario di trasferimento




=== 14 luglio 2025



==== Supporto per la replica dei dati tra due file system FSx per ONTAP

La replica dei dati è ora disponibile tra due file system FSx per ONTAP dalla canvas nella console BlueXP .

link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/use/task-manage-fsx-systems.html#replicate-data["Replicare i dati"]



== Archiviazione Amazon S3



== Archiviazione BLOB di Azure



== Azure NetApp Files



== Backup e ripristino



== Classificazione dei dati



== Cloud Volumes ONTAP



== Copia e sincronizza



== Consulente digitale



== Licenses and subscriptions



=== 06 ottobre 2025



==== BlueXP è ora NetApp Console

NetApp Console, basata sulle fondamenta BlueXP migliorate e ristrutturate, offre una gestione centralizzata dello storage NetApp e NetApp Data Services in ambienti on-premise e cloud di livello aziendale, offrendo informazioni in tempo reale, flussi di lavoro più rapidi e un'amministrazione semplificata, il tutto in modo altamente sicuro e conforme.

Per i dettagli su cosa è cambiato, vedere illink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Note sulla versione NetApp Console"] .



=== 10 marzo 2025



==== Possibilità di rimuovere gli abbonamenti

Ora puoi rimuovere gli abbonamenti dal portafoglio digitale se li hai annullati.



==== Visualizza la capacità consumata per gli abbonamenti Marketplace

Quando si visualizzano gli abbonamenti PAYGO, ora è possibile visualizzare la capacità consumata dell'abbonamento.



=== 10 febbraio 2025

Il BlueXP digital wallet è stato riprogettato per semplificarne l'utilizzo e ora offre una gestione aggiuntiva di abbonamenti e licenze.



==== Nuova dashboard Panoramica

La homepage del portafoglio digitale presenta una dashboard aggiornata delle licenze NetApp e degli abbonamenti Marketplace, con la possibilità di analizzare nel dettaglio servizi specifici, tipi di licenza e azioni richieste.



==== Configurazione degli abbonamenti alle credenziali

Il BlueXP digital wallet ora ti consente di configurare i tuoi abbonamenti in base alle credenziali del provider. Solitamente questa operazione viene eseguita quando si sottoscrive per la prima volta un abbonamento Marketplace o un contratto annuale. In precedenza la modifica delle credenziali dell'abbonamento poteva essere effettuata solo nella pagina Credenziali.



==== Associazione degli abbonamenti alle organizzazioni

Ora puoi aggiornare l'organizzazione a cui è associato un abbonamento direttamente dal portafoglio digitale.



==== Gestione delle licenze Cloud Volume ONTAP

Ora puoi gestire le licenze Cloud Volumes ONTAP tramite la home page o la scheda *Licenze dirette*. Utilizza la scheda *Abbonamenti Marketplace* per visualizzare le informazioni sul tuo abbonamento.



=== 5 marzo 2024



==== BlueXP disaster recovery

Il BlueXP digital wallet ora consente di gestire le licenze per il BlueXP disaster recovery. È possibile aggiungere licenze, aggiornare licenze e visualizzare i dettagli sulla capacità concessa in licenza.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Scopri come gestire le licenze per i servizi dati BlueXP"]



=== 30 luglio 2023



==== Miglioramenti dei report di utilizzo

Sono ora disponibili diversi miglioramenti ai report di utilizzo Cloud Volumes ONTAP :

* L'unità TiB è ora inclusa nel nome delle colonne.
* È ora incluso un nuovo campo _node(s)_ per i numeri di serie.
* Nel report sull'utilizzo delle VM di archiviazione è ora inclusa una nuova colonna _Tipo di carico di lavoro_.
* I nomi degli ambienti di lavoro sono ora inclusi nei report sulle VM di archiviazione e sull'utilizzo dei volumi.
* Il tipo di volume _file_ è ora etichettato _Primario (lettura/scrittura)_.
* Il tipo di volume _secondario_ è ora etichettato _Secondario (DP)_.


Per ulteriori informazioni sui report di utilizzo, fare riferimento a https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["Scarica i report di utilizzo"] .



== Ripristino dopo un disastro



== Sistemi della serie E



== Pianificazione del ciclo di vita



== Caching dei bordi

Il servizio di edge caching è stato rimosso il 7 agosto 2024.



== Google Cloud NetApp Volumes



== Google Cloud Storage



=== 06 ottobre 2025



==== BlueXP è ora NetApp Console

NetApp Console, basata sulle fondamenta BlueXP migliorate e ristrutturate, offre una gestione centralizzata dello storage NetApp e NetApp Data Services in ambienti on-premise e cloud di livello aziendale, offrendo informazioni in tempo reale, flussi di lavoro più rapidi e un'amministrazione semplificata, il tutto in modo altamente sicuro e conforme.

Per i dettagli su cosa è cambiato, vedere illink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Note sulla versione NetApp Console"] . == 10 luglio 2023



==== Possibilità di aggiungere nuovi bucket e gestire quelli esistenti da BlueXP

È possibile visualizzare i bucket di Google Cloud Storage su BlueXP Canvas per un bel po' di tempo. Ora puoi aggiungere nuovi bucket e modificare le proprietà di quelli esistenti direttamente da BlueXP. https://docs.netapp.com/us-en/storage-management-google-cloud-storage/task-add-gcp-bucket.html["Scopri come aggiungere nuovi bucket di Google Cloud Storage"] .



== Keystone



== Kubernetes

Il supporto per l'individuazione e la gestione dei cluster Kubernetes è stato rimosso il 7 agosto 2024.



== Rapporti di migrazione

Il servizio di segnalazione delle migrazioni è stato rimosso il 7 agosto 2024.



== Cluster ONTAP on-prem



== Resilienza operativa

Le funzionalità di resilienza operativa sono state rimosse il 22 agosto 2025.



== Resilienza al ransomware



== Bonifica

Il servizio di bonifica è stato rimosso il 22 aprile 2024.



== Replicazione



== Aggiornamenti software



== StorageGRID



== Cloud Tiering



=== 06 ottobre 2025



==== Il BlueXP tiering è ora NetApp Cloud Tiering

Il BlueXP tiering è stato rinominato NetApp Cloud Tiering.



==== BlueXP è ora NetApp Console

NetApp Console, basata sulle fondamenta BlueXP migliorate e ristrutturate, offre una gestione centralizzata dello storage NetApp e NetApp Data Services in ambienti on-premise e cloud di livello aziendale, offrendo informazioni in tempo reale, flussi di lavoro più rapidi e un'amministrazione semplificata, il tutto in modo altamente sicuro e conforme.

Per i dettagli su cosa è cambiato, vederelink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Note sulla versione NetApp Console"] .



=== 09 agosto 2023



==== Utilizza un prefisso personalizzato per il nome del bucket

In passato era necessario utilizzare il prefisso predefinito "fabric-pool" per definire il nome del bucket, ad esempio _fabric-pool-bucket1_.  Ora puoi usare un prefisso personalizzato quando assegni un nome al tuo bucket.  Questa funzionalità è disponibile solo quando si suddividono i dati in livelli su Amazon S3. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["Saperne di più"] .



==== Cerca un cluster in tutti i connettori BlueXP

Se si utilizzano più connettori per gestire tutti i sistemi di archiviazione nel proprio ambiente, alcuni cluster su cui si desidera implementare la suddivisione in livelli potrebbero trovarsi in connettori diversi.  Se non sei sicuro di quale connettore gestisca un determinato cluster, puoi effettuare una ricerca tra tutti i connettori utilizzando Cloud Tiering. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["Saperne di più"] .



=== 04 luglio 2023



==== Regola la larghezza di banda per trasferire i dati inattivi

Quando si attiva Cloud Tiering, ONTAP può utilizzare una quantità illimitata di larghezza di banda di rete per trasferire i dati inattivi dai volumi nel cluster all'archiviazione degli oggetti.  Se noti che il traffico a livelli influisce sui normali carichi di lavoro degli utenti, puoi limitare la quantità di larghezza di banda che può essere utilizzata durante il trasferimento. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["Saperne di più"] .



==== Evento di suddivisione in livelli visualizzato nel Centro notifiche

L'evento di suddivisione in livelli "Suddivisione in livelli di dati aggiuntivi dal cluster <nome> all'archiviazione oggetti per aumentare l'efficienza dell'archiviazione" ora viene visualizzato come notifica quando un cluster suddivide in livelli meno del 20% dei suoi dati inattivi, inclusi i cluster che non suddividono in livelli alcun dato.

Questa notifica è una "Raccomandazione" per aiutarti a rendere i tuoi sistemi più efficienti e a risparmiare sui costi di archiviazione. Fornisce un collegamento al https://www.netapp.com/data-services/tiering/tco-calculator/["Calcolatore del costo totale di proprietà e dei risparmi di Cloud Tiering"^] per aiutarti a calcolare il risparmio sui costi.



== Memorizzazione nella cache del volume



== Fabbrica del carico di lavoro



=== 06 ottobre 2025



==== La BlueXP workload factory ora è NetApp Workload Factory

BlueXP è stato rinominato e riprogettato per riflettere meglio il ruolo che svolge nella gestione dell'infrastruttura dati.  Di conseguenza, BlueXP workload factory è stato rinominato NetApp Workload Factory.



==== Integrazione Ask Me con MCP

Ask Me, l'assistente AI di Workload Factory, è integrato con il Model Context Protocol (MCP).  Utilizzando MCP, Ask Me interagisce in modo sicuro con ambienti esterni e interroga gli strumenti API per fornire risposte personalizzate in base al tuo specifico ambiente di archiviazione.



=== 05 ottobre 2025



==== Nuova notifica per Storage

Il servizio di notifica NetApp Workload Factory include la notifica per problemi ben progettati per l'archiviazione.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Notifiche per NetApp Workload Factory"]



=== 09 settembre 2025



==== Nuova notifica per Storage

Il servizio di notifica BlueXP workload factory include la notifica per la gestione automatica della capacità per l'archiviazione.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Notifiche per la BlueXP workload factory"]
