---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Scopri le modifiche più recenti apportate alle funzionalità e ai servizi dati che fanno parte della NetApp Console. 
---
= Modifiche recenti nella NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le modifiche più recenti apportate alle funzionalità e ai servizi dati che fanno parte della NetApp Console.  Per una cronologia completa delle versioni, vai alink:release-notes-index.html["set completo di note di rilascio"] per ogni singolo servizio.



== Servizi deprecati



=== Caching dei bordi

Il servizio di edge caching è stato rimosso il 7 agosto 2024.



=== Kubernetes

Il supporto per l'individuazione e la gestione dei cluster Kubernetes è stato rimosso il 7 agosto 2024.



=== Rapporti di migrazione

Il servizio di segnalazione delle migrazioni è stato rimosso il 7 agosto 2024.



=== Resilienza operativa

Le funzionalità di resilienza operativa sono state rimosse il 22 agosto 2025.



=== Bonifica

Il servizio di bonifica è stato rimosso il 22 aprile 2024.



== 19 gennaio 2026



=== Backup e ripristino



==== Miglioramenti dei carichi di lavoro del volume ONTAP

Questa versione dei carichi di lavoro del volume ONTAP introduce le seguenti funzionalità migliorate:

*Supporto per più bucket*: (Anteprima privata) A partire da ONTAP 9.17.1 e versioni successive, è possibile proteggere i volumi all'interno di un sistema con un massimo di 6 bucket per sistema su diversi provider cloud.

link:prev-ontap-backup-manage.html["Scopri di più sul backup dei dati del volume ONTAP utilizzando NetApp Backup and Recovery"].



==== Miglioramenti dei carichi di lavoro VMware

Questa versione dei carichi di lavoro VMware introduce le seguenti funzionalità avanzate:

* Il supporto per i carichi di lavoro VMware è ora generalmente disponibile (GA) in NetApp Backup and Recovery.
* Ora puoi ripristinare i file e le cartelle del sistema operativo guest.


https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Scopri di più sul ripristino delle VM VMware con NetApp Backup and Recovery"].

https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore-guest-files-and-folders-overview.html["Scopri di più sul ripristino di file e cartelle guest"].



==== Miglioramenti dell'anteprima dei carichi di lavoro Hyper-V

Questa versione dei carichi di lavoro Hyper-V introduce le seguenti funzionalità avanzate:

* Ora è possibile ripristinare i backup e gli snapshot delle VM Hyper-V in una posizione alternativa. Questa funzionalità è utile se si desidera gestire le versioni di una VM su host Hyper-V diversi.
* Le macchine virtuali Hyper-V fornite da System Center Virtual Machine Manager (SCVMM) e ospitate su una condivisione CIFS sono ora supportate da NetApp Backup and Recovery.
* Ora puoi modificare i gruppi di protezione.



NOTE: Solo in questa versione non è possibile aggiornare i plugin NetApp per Hyper-V o Windows utilizzando l'opzione *Aggiorna* nel menu Azioni. In alternativa, rimuovere ciascun host Hyper-V e aggiungerlo nuovamente per aggiornare i plugin.

https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-restore.html["Scopri di più sul ripristino delle VM Hyper-V con NetApp Backup and Recovery"].



==== Miglioramenti dell'anteprima dei carichi di lavoro KVM

L'anteprima dei carichi di lavoro KVM ora supporta l'integrazione con la piattaforma di gestione Apache CloudStack, consentendo di proteggere gli host KVM e le macchine virtuali gestite da Apache CloudStack.

Per i dettagli sulla protezione dei carichi di lavoro KVM, fare riferimento a https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["Panoramica sulla protezione dei carichi di lavoro KVM"] .



=== Resilienza al ransomware



==== Volumi non supportati

I report di Ransomware Resilience ora acquisiscono informazioni sui volumi supportati e non supportati nel report **Riepilogo**. Utilizzare queste informazioni per diagnosticare il motivo per cui i volumi di un sistema potrebbero non essere idonei alla protezione anti-ransomware.

Per maggiori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-reports.html["Scarica i report in Ransomware Resilience"^].



=== Keystone

Aggiornamenti nella dashboard Keystone nella NetApp Console:



==== Modifica abbonamento non disponibile

L'opzione per modificare la capacità impegnata per gli abbonamenti Keystone non è attualmente disponibile. Questa funzionalità verrà reintrodotta in una versione futura.



== 14 gennaio 2026



=== Classificazione dei dati



==== Versione 1.50

Questa versione di Data Classification include correzioni di bug e i seguenti aggiornamenti:

.Miglioramenti della classificazione personalizzata
Data Classification ora supporta la creazione di categorie personalizzate per i tuoi dati. È possibile caricare file per perfezionare un modello di intelligenza artificiale che Data Classification utilizza per applicare il marcatore di categoria ai dati. L'interfaccia per tutte le classificazioni personalizzate è stata migliorata.

Per maggiori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-data-classification/task-custom-classification.html["Crea una classificazione personalizzata"^].

.Definizione di dati obsoleti personalizzati
La classificazione dei dati ora consente di personalizzare la definizione dei dati obsoleti in modo che si adatti alle esigenze della tua organizzazione. In precedenza, per dati obsoleti si intendevano tutti i dati la cui ultima modifica risaliva a tre anni prima. Ora è possibile identificare i dati obsoleti in base alla data dell'ultimo accesso o dell'ultima modifica; il periodo di tempo può variare da 6 mesi a 10 anni fa.

Per maggiori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-data-classification/task-stale-data.html["Personalizza la definizione dei dati obsoleti"^].

.Prestazioni migliorate
I tempi di caricamento per tutte le pagine della Classificazione dati, del report di mappatura dati e dei filtri nella pagina Indagine sono stati ridotti.

.Tempo stimato per i rapporti di indagine
Quando si scarica un rapporto di indagine, la classificazione dei dati ora visualizza il tempo stimato necessario per il completamento del download.



== 12 gennaio 2026



=== Configurazione e amministrazione della console



==== Agente console 4.3.0

La versione 4.3.0 supporta sia la modalità standard che quella limitata.

Questa versione dell'agente Console include miglioramenti della sicurezza, correzioni di bug e le seguenti funzionalità:

.Capacità di convalidare le connessioni di rete degli agenti della console
Ora è possibile convalidare le connessioni di rete degli agenti Console connessi direttamente dalla NetApp Console. Questa funzionalità consente di verificare la connettività e di risolvere i problemi relativi agli agenti della console.

link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access["Scopri come eseguire controlli di configurazione sugli agenti della console."]



==== Amministrazione NetApp Console

Questa versione include quanto segue:

.Accesso basato sui ruoli per gruppi federati nella NetApp Console
NetApp Console supporta l'assegnazione di ruoli a gruppi federati (ad esempio, gruppi di Active Directory), consentendo agli amministratori di automatizzare l'onboarding e l'offboarding degli utenti in base all'appartenenza al gruppo nel provider di identità (IdP) dell'organizzazione. Questa funzionalità riduce il sovraccarico amministrativo e garantisce un accesso sicuro e coerente aggiornando istantaneamente l'accesso alla Console man mano che cambiano le appartenenze al gruppo.

link:https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html#add-a-federated-group-to-your-organization["Scopri come fornire l'accesso a un gruppo federato alla tua organizzazione."]

.Supporto per la federazione quando NetApp Console è in modalità limitata
Ora puoi abilitare la federazione per un'organizzazione NetApp Console in modalità limitata. Ciò consente agli utenti di accedere alla Console utilizzando le proprie credenziali aziendali, mantenendo al contempo i vantaggi di sicurezza della modalità con restrizioni.

.Modalità di sola lettura
È possibile impostare un'organizzazione NetApp Console in modalità di sola lettura. In modalità di sola lettura, gli utenti possono visualizzare risorse e impostazioni, ma non possono apportare modifiche. Un amministratore dell'organizzazione o un super amministratore può abilitare la modalità di sola lettura per un'organizzazione. Quando la modalità di sola lettura è abilitata, gli utenti con ruoli amministrativi devono elevare manualmente le proprie autorizzazioni per apportare le modifiche necessarie.

link:https://docs.netapp.com/us-en/console-setup-admin/task-enable-read-only-mode.html["Scopri come abilitare la modalità di sola lettura per un'organizzazione Console."]

link:https://docs.netapp.com/us-en/console-setup-admin/task-user-settings.html["Scopri come valorizzare il tuo ruolo quando la tua organizzazione è in modalità di sola lettura."]



=== Ripristino dopo un disastro



==== Supporto per più agenti Console in ambienti on-premise

Se utilizzi il Disaster Recovery in locale, ora puoi distribuire un agente Console per ogni istanza di vCenter, migliorando la resilienza.

Ad esempio, se si dispone di due siti (siti A e B), il sito A può avere l'agente console A collegato a vCenter 1, distribuzione ONTAP 1 e distribuzione ONTAP 2. Il sito B può avere l'agente Console B collegato alle distribuzioni vCenter 2 e ONTAP 3 e 4.

Per informazioni sull'agente Console in Disaster Recovery, vedere link:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/dr-prerequisites.html#netapp-console-prerequisites["Creare l'agente della console"^].



==== Aggiungere VM dopo il failover per i piani di replicazione utilizzando la protezione basata su datastore

Quando viene attivato il failover, qualsiasi piano di replica che utilizza la protezione basata su datastore include le VM aggiunte al datastore, a condizione che siano state rilevate. È necessario fornire i dettagli di mappatura per le VM aggiunte prima del completamento del failover.

Per maggiori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["Failover delle applicazioni"^].



==== Nuove notifiche e-mail

Disaster Recovery ora fornisce notifiche e-mail per i seguenti eventi:

* Avvicinamento al limite di utilizzo della capacità
* Generazione del report completata
* Fallimenti lavorativi
* Scadenza o violazioni della licenza




==== Miglioramenti di Swagger

Ora è possibile accedere alla documentazione di Swagger dall'interno di Disaster Recovery. In Disaster Recovery, seleziona **Impostazioni**, quindi **Documentazione API** per collegarti a Swagger oppure visita questo URL nella modalità di navigazione in incognito/privata del tuo browser: link:https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas"^].



==== Interfacce utente migliorate

Disaster Recovery ora fornisce avvisi e risoluzioni degli errori migliorati. Questa versione corregge un errore che impediva la visualizzazione dei lavori annullati nell'interfaccia utente. Ora i lavori annullati sono visibili. È presente anche un nuovo avviso quando la stessa rete di destinazione viene mappata su più reti di origine diverse.



==== Mantieni la struttura delle cartelle della VM aggiunta come predefinita nei piani di replica

Quando si crea una replica, la nuova impostazione predefinita è quella di mantenere la struttura delle cartelle della VM. Se la destinazione di ripristino non dispone della gerarchia di cartelle originale, Disaster Recovery la crea. È possibile deselezionare questa opzione per ignorare la gerarchia delle cartelle originale.

Per maggiori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"^].



=== Resilienza al ransomware



==== Replica gli snapshot su ONTAP

Ransomware Resilience ora supporta l'aggiunta della replica degli snapshot a un sito ONTAP secondario. Con i gruppi di protezione che utilizzano un criterio di replica, è possibile replicare sulla stessa destinazione o su destinazioni diverse per ogni carico di lavoro. È possibile creare una strategia di protezione dal ransomware che includa la replica oppure utilizzare la strategia predefinita.

Per maggiori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-protect.html["Proteggi i carichi di lavoro con Ransomware Resilience"^].



==== Escludere i carichi di lavoro dalla resilienza del ransomware

Ransomware Resilience ora supporta l'esclusione di carichi di lavoro specifici in un sistema dalla protezione e dalla dashboard di Ransomware Resilience. È possibile escludere i carichi di lavoro dopo l'individuazione e reincluderli se si desidera aggiungere la protezione ransomware. Non ti verrà addebitato alcun costo per i carichi di lavoro esclusi.

Per maggiori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-discover.html#exclude-workloads["Escludi carichi di lavoro"^].



==== Contrassegna gli avvisi come in revisione

Ransomware Resilience ora consente di contrassegnare gli avvisi come "In revisione". Utilizza l'etichetta "In revisione" per migliorare la chiarezza all'interno del tuo team durante la selezione e la gestione delle minacce ransomware attive.

Per maggiori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html["Gestisci gli avvisi in Ransomware Resilience"^].



=== Cloud Volumes ONTAP



==== Opzione di fatturazione preferita per Cloud Volumes ONTAP

Ora puoi selezionare un'opzione di fatturazione preferita per calcolare l'utilizzo e gli eccedenti Cloud Volumes ONTAP . Dal 25 giugno 2025, data di disponibilità limitata del modello di licenza Bring Your Own Licenses (BYOL), NetApp ha aggiunto metodi di addebito preferiti nella sezione *Licenze e abbonamenti* della NetApp Console. Puoi utilizzare l'abbonamento annuale al marketplace per la fatturazione e gli eccedenti oppure il modello BYOL esistente come opzione preferita. Ciò ti offre la flessibilità di scegliere il metodo di addebito più adatto alla strategia finanziaria e ai modelli di utilizzo della tua organizzazione.

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing-charging.html#billing-preferences-and-overages["Preferenze di fatturazione e superamenti"^].



== 10 dicembre 2025



=== Configurazione e amministrazione della console



==== Agente console 4.2.0

La versione 4.2.0 supporta sia la modalità standard che quella limitata.

Questa versione dell'agente Console include miglioramenti della sicurezza, correzioni di bug e le seguenti funzionalità:

.Supporto per Google Cloud Infrastructure Manager
NetApp ora utilizza Google Cloud Infrastructure Manager (IM) anziché Google Cloud Deployment Manager per distribuire gli agenti e gestirli in Google Cloud. Questa modifica è stata apportata perché Google disapproverà link:https://docs.cloud.google.com/deployment-manager/docs/deprecations["Cloud Deployment Manager"].

* Tutti i nuovi agenti 4.2.0 e versioni successive utilizzano Infrastructure Manager e dovresti aggiornare sia le autorizzazioni dell'account utente che quelle dell'account di servizio utilizzate per la distribuzione. link:https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html#gcp-permissions-change-log["Visualizza il registro delle modifiche delle autorizzazioni."^]
* Quando si distribuisce un agente, il sistema crea anche un bucket Google Cloud per archiviare i file di distribuzione.


.Controlli di configurazione migliorati per gli agenti della console
* L'agente Console ora verifica la presenza di endpoint obsoleti durante l'esecuzione di un controllo della configurazione. Se non è stato effettuato l'aggiornamento al nuovo elenco di endpoint per la versione 4.0.0 o successiva, le installazioni riescono se il sistema riesce a raggiungere l'elenco di endpoint precedente. link:https://docs.netapp.com/us-en/console-setup-admin/reference-networking-saas-console-previous.html#update-endpoint-list["Scopri di più sugli endpoint richiesti per gli agenti della console."^]
* Eseguire controlli di configurazione sugli agenti della console installati dalla console o dalla console di manutenzione dell'agente per verificare la connettività e risolvere i problemi. link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access["Scopri come eseguire controlli di configurazione sugli agenti della console."^]


.Scarica direttamente il software dell'agente dalla NetApp Console
Quando è necessario installare manualmente un agente, è possibile accedere al software dell'agente direttamente dalla NetApp Console , oltre che dal sito di supporto NetApp . link:https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-on-prem.html#install-the-console-agent-manually["Scopri come scaricare il software dell'agente Console direttamente dalla NetApp Console."^]



==== Amministrazione NetApp Console

Questa versione include quanto segue:

.Possibilità di impostare notifiche per le credenziali in scadenza
Imposta notifiche per la scadenza delle credenziali sugli account di servizio e sulle federazioni. Scegli tra sette o 30 giorni. La Console visualizza notifiche e invia e-mail agli utenti con il ruolo appropriato. Gli amministratori dell'organizzazione ricevono notifiche sugli account di servizio. Gli amministratori dell'organizzazione, gli amministratori della federazione e i visualizzatori della federazione ricevono notifiche sulla federazione.

.Gli accessi locali non sono disponibili dopo aver abilitato la federazione
Dopo aver attivato la federazione per un'organizzazione Console, gli utenti non possono utilizzare gli accessi locali e vengono indirizzati agli accessi federati.

.Miglioramenti dell'usabilità per le pagine di gestione dell'archiviazione
Le informazioni dettagliate sui sistemi ONTAP on-premise (e FSx per ONTAP) sono ora più facili da visualizzare e gestire dalle pagine di gestione dell'archiviazione.

* La pagina * Discoverable systems* separa le informazioni riepilogative dalla visualizzazione a schede dei sistemi disponibili, semplificando la visualizzazione di informazioni complete sui sistemi rilevabili.




=== Cluster ONTAP on-premise



==== Miglioramenti dell'usabilità durante la visualizzazione dei sistemi ONTAP dalla NetApp Console (solo modalità standard)

La pagina *Sistemi* nella NetApp Console presenta miglioramenti per chiarezza e usabilità nella gestione di volumi e cluster. Questi aggiornamenti allineano maggiormente l'esperienza con System Manager per le versioni ONTAP più recenti e semplificano la navigazione.

.Capacità del cluster inclusa per le versioni ONTAP 9.5 e successive (solo modalità standard della console)
La pagina *Sistemi > Panoramica* mostra le dimensioni del cluster insieme alla versione ONTAP per i cluster che eseguono ONTAP 9.5 e versioni successive.

Per NetApp Console in modalità limitata o per le versioni ONTAP 9.5 e precedenti, le informazioni sul volume fornito rimangono invariate.

.La scheda Volumi nella pagina Sistemi è impostata per impostazione predefinita sulla visualizzazione griglia se si dispone di più di 20 cluster ONTAP locali
Se nella NetApp Console sono gestiti più di 20 cluster ONTAP locali, la scheda *Volume* utilizza per impostazione predefinita la visualizzazione griglia per una navigazione più semplice. La visualizzazione delle schede è disabilitata.

Questa modifica si applica solo alla modalità standard e alle versioni ONTAP 9.6 e successive.



== 09 dicembre 2025



=== Ripristino dopo un disastro



==== Conservazione della gerarchia delle cartelle

Per impostazione predefinita, Disaster Recovery mantiene la gerarchia dell'inventario delle VM (struttura delle cartelle) durante il failover. Se la destinazione di ripristino non dispone della cartella richiesta, Disaster Recovery la crea.

Ora è possibile ignorare questa impostazione designando una nuova cartella VM padre o deselezionando l'opzione **Mantieni gerarchia cartelle originale**.

Per maggiori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["Creare un piano di replicazione"].



==== Aggiornamento semplificato dell'agente della console

Disaster Recovery ora supporta un processo semplificato per l'utilizzo di più agenti Console in un ambiente di lavoro. Per passare da un agente Console all'altro, è necessario modificare la configurazione di vCenter, riscoprire le credenziali e aggiornare i piani di replica per utilizzare il nuovo agente Console.

Per maggiori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-disaster-recovery/reference/switch-console-agent.html["Agenti della console Switch"].



== 08 dicembre 2025



=== Backup e ripristino



==== Miglioramenti dell'anteprima dei carichi di lavoro VMware

La versione di anteprima dei carichi di lavoro VMware introduce le seguenti funzionalità avanzate:

* Ora puoi ripristinare backup e snapshot in una posizione alternativa. Questa funzionalità è utile se si desidera gestire le versioni di una VM su diverse distribuzioni VMware vCenter, host VMware ESXi o datastore VMware.


link:br-use-vmware-restore.html["Scopri di più sul ripristino delle VM VMware con NetApp Backup and Recovery"].

* Ora è possibile ripristinare specifici dischi virtuali VMware (immagini VMDK) da una posizione primaria o secondaria, consentendo un controllo più granulare sul ripristino dei dati della VM.


link:br-use-vmware-restore-vmdks-from-backups.html["Scopri di più sul ripristino dei dischi virtuali VMware con NetApp Backup and Recovery"].



=== Classificazione dei dati



==== Versione 1.49

Questa versione di Data Classification include correzioni di bug e i seguenti aggiornamenti:

.Monitora le metriche e le prestazioni nella dashboard di monitoraggio dello stato
Data Classification ora fornisce una dashboard di monitoraggio dello stato di salute, che fornisce un monitoraggio in tempo reale delle risorse e informazioni dettagliate sull'utilizzo della memoria, sull'utilizzo del disco, sull'utilizzo del disco e altro ancora. Grazie alle informazioni fornite dalla dashboard di monitoraggio dello stato, puoi esaminare l'infrastruttura della tua distribuzione e ottenere informazioni utili per ottimizzare storage e prestazioni.

Per maggiori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-data-classification/task-health-monitor.html["Monitorare lo stato di salute della classificazione dei dati"].

.Prestazioni di caricamento migliorate
Le prestazioni di caricamento di tutte le pagine in Data Classification sono state migliorate per creare un'esperienza utente più efficiente.



=== Resilienza al ransomware



==== Il blocco delle estensioni è abilitato a livello di carico di lavoro

Quando si abilita il blocco delle estensioni, ora viene abilitato a livello di carico di lavoro anziché a livello di VM di archiviazione.



==== Modifica lo stato dell'avviso sul comportamento dell'utente

Ransomware Resilience ora consente di modificare lo stato degli avvisi sul comportamento degli utenti. È possibile ignorare e risolvere manualmente gli avvisi.

Per maggiori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html["Gestisci gli avvisi in Ransomware Resilience"^].



==== Supporto per più agenti della console

Ransomware Resilience ora supporta l'utilizzo di più agenti Console per gestire gli stessi sistemi.

Per ulteriori informazioni sugli agenti della console, vederelink:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-setup.html["Creare un agente Console"] .



=== Cloud Volumes ONTAP



==== Possibilità di migliorare le prestazioni dei dischi Premium SSD v2 in Azure

Ora puoi migliorare le prestazioni di Premium SSD v2 Managed Disks in Azure modificando i parametri IOPS e velocità effettiva. Utilizzando questa funzionalità, puoi ottimizzare le prestazioni di archiviazione dei tuoi sistemi in base ai requisiti del carico di lavoro.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-perf-params-azure.html["Gestisci le prestazioni del disco Premium SSD v2 per Cloud Volumes ONTAP in Azure"^].



==== Semplificazione della tariffazione eccedente per le licenze Essentials

Per i contratti annuali/offerte private del marketplace Cloud Volumes ONTAP , i calcoli del sovrapprezzo per le licenze Essentials sono ora allineati con i pacchetti Bring Your Own License (BYOL). In precedenza, gli eccessi venivano fatturati in base alle tariffe orarie di mercato per l'esatto pacchetto Essentials. Ora, se il tuo contratto annuale sul marketplace include più pacchetti Essentials, la NetApp Console addebita i costi aggiuntivi per un pacchetto Essentials rispetto alla capacità disponibile di un pacchetto Essentials più costoso nel tuo abbonamento. Ciò semplifica i calcoli del sovrapprezzo per i pacchetti Essentials e garantisce una transizione graduale dalla licenza BYOL a un modello basato su abbonamento.

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing-charging.html#how-overages-are-charged-for-essentials-licenses["Come vengono addebitati gli eccessi per le licenze Essentials"^]



==== Supporto per le serie di dimensioni Azure Edsv6

A partire da Cloud Volumes ONTAP 9.17.1, è possibile distribuire VM della serie Azure Edsv6 tramite la NetApp Console per le nuove istanze Cloud Volumes ONTAP . Cloud Volumes ONTAP 9.17.1 e versioni successive supporteranno solo le VM di seconda generazione per le nuove distribuzioni. Queste macchine di seconda generazione sono compatibili con le tecnologie più recenti, come Unified Extensible Firmware Interface (UEFI), sistemi Azure Boost e NVMe. Sono ideali per sistemi e applicazioni ad alta intensità di memoria che necessitano di un'archiviazione locale veloce, come server di database e motori di analisi.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html#supported-configurations-by-license["Configurazioni supportate per Cloud Volumes ONTAP in Azure"^]



=== Keystone

Nuovi miglioramenti nella dashboard Keystone nella NetApp Console:



==== Etichetta di capacità di burst accumulata rinominata

L'etichetta *Capacità burst accumulata* viene rinominata in *Burst accumulato*.



== 01 dicembre 2025



=== Ripristino dopo un disastro



==== Supporto per Google Cloud VMware Engine tramite Google Cloud NetApp Volumes

NetApp Disaster Recovery ora supporta Google Cloud VMware Engine utilizzando Google Cloud NetApp Volumes per le operazioni di migrazione, failover, failback e test. Questa integrazione consente flussi di lavoro di disaster recovery senza interruzioni tra ambienti on-premise e Google Cloud.

Assicurati di rivedere illink:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/dr-prerequisites.html["prerequisiti"] Elink:https://docs.netapp.com/us-en/data-services-disaster-recovery/release-notes/dr-limitations.html["limitazioni"] per Google Cloud.



== 27 novembre 2025



=== Google Cloud NetApp Volumes



==== Modifiche alle credenziali di Google Cloud Platform

Man mano che i clienti configurano e autorizzano più sistemi Google Cloud NetApp Volumes , il modo in cui vengono gestite le credenziali è cambiato.

Le credenziali dei sistemi NetApp Volumes sono ora archiviate su un backend cloud di Google, come il servizio Cloud Key Management o simile, e le credenziali di rappresentazione dell'account di servizio vengono utilizzate durante la creazione di un nuovo sistema.



== 24 novembre 2025



=== Keystone

Nuovi miglioramenti nella dashboard Keystone nella NetApp Console:



==== ID di tracciamento per abbonamenti con copertura gap

Nella casella di notifica *Completa la tua copertura* in *Monitoraggio > Monitor avvisi*, ogni abbonamento ora visualizza il proprio ID di monitoraggio accanto al numero di abbonamento.



== 17 novembre 2025



=== Amazon FSX per ONTAP



==== System Manager disponibile quando si utilizza un collegamento AWS Lambda

L'interfaccia ONTAP System Manager può essere utilizzata con un collegamento AWS Lambda per eseguire operazioni ONTAP avanzate. Ciò fornisce un'alternativa all'utilizzo di un agente Console con System Manager per la gestione di un file system FSx for ONTAP direttamente dalla Console. link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Scopri come utilizzare i collegamenti per operazioni ONTAP avanzate"^]



== 11 novembre 2025



=== Amazon FSX per ONTAP



==== Supporto per la replica tra sistemi ONTAP locali e file system FSx per ONTAP

La replica dei dati è disponibile tra un sistema ONTAP locale e un file system FSx for ONTAP dalla pagina Sistemi NetApp Console .

link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/use/task-manage-fsx-systems.html#replicate-data["Replicare i dati"]



== 10 novembre 2025



=== Licenses and subscriptions



==== Gestisci le preferenze di fatturazione

Ora puoi configurare e gestire le *Preferenze di fatturazione* direttamente nella NetApp Console. Questo miglioramento consente agli amministratori di definire e visualizzare come l'utilizzo della capacità, i rinnovi e i costi vengono fatturati tra le licenze NetApp dirette, gli abbonamenti al cloud marketplace e l'accordo Keystone .

Per maggiori informazioni, vedere illink:https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["Documentazione sulle preferenze di fatturazione"^] .



=== Configurazione e amministrazione della console



==== Agente console 4.1.0

Questa versione dell'agente Console include miglioramenti della sicurezza, correzioni di bug e le seguenti funzionalità:

La versione 4.1.0 è disponibile per la modalità standard e la modalità limitata.

.Indicatori di stato dell'agente rinominati
Gli indicatori di stato per l'agente della console sono stati rinominati da *Attivo* e *Inattivo* a *Connesso* e *Disconnesso* per renderne più chiaro lo scopo.

.Supporto per Red Hat Enterprise Linux (RHEL) 9.6 e Podman 5.4.0
Quando si installa manualmente un agente Console, l'agente ora supporta RHEL 9.6 con Podman 5.4.0. Inoltre, quando si utilizza RHEL 9 e versioni successive, NetApp supporta podman-compose 1.5.0. link:https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-on-prem.html["Visualizza i requisiti del sistema operativo"].



==== Amministrazione NetApp Console

Questa versione include quanto segue:

.Nuovo indirizzo email per le notifiche NetApp Console
L'indirizzo email che invia le notifiche NetApp Console è cambiato da *service@console.bluexp.netapp.com* a *service@console.netapp.com*. NetApp consiglia di aggiornare tutte le regole e-mail per consentire *service@console.netapp.com*, per essere certi di continuare a ricevere le notifiche e-mail NetApp Console .



=== Classificazione dei dati



==== Versione 1.48

Questa versione di Data Classification include correzioni di bug, miglioramenti della sicurezza e delle prestazioni.

.Maggiore chiarezza nell'avanzamento della scansione
Le configurazioni di scansione ora includono informazioni più approfondite sul completamento della scansione. In precedenza, la barra di avanzamento veniva visualizzata solo durante l'esecuzione della scansione. Ora la barra di avanzamento rimane visibile anche dopo il completamento per confermare che le scansioni sono state completate correttamente. È anche possibile visualizzare il numero di file mappati e scansionati.

Per ulteriori informazioni sulle impostazioni di scansione, vedere link:https://docs.netapp.com/us-en/data-services-data-classification/task-managing-repo-scanning.html#view-the-scan-status-for-your-repositories["Modifica le impostazioni di scansione NetApp Data Classification per i tuoi repository"^].



=== Ripristino dopo un disastro



==== Supporto failover a cascata

Ora è possibile configurare una relazione a cascata in ONTAP e utilizzare qualsiasi parte di tale relazione di replica per il ripristino di emergenza.



==== Ridurre il supporto hardware VMware durante la registrazione

Disaster Recovery ora supporta il downgrade dell'hardware VMware a una versione precedente di vSphere durante la registrazione. Questa funzionalità è utile quando l'host ESX di origine esegue una versione successiva a quella del sito di ripristino di emergenza.

Per maggiori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html#select-vcenter-servers["Creare un piano di replica in NetApp Disaster Recovery"].



==== Arresto graduale

Disaster Recovery ora arresta correttamente le VM anziché spegnerle. Se una determinata VM impiega più di dieci minuti per spegnersi, Disaster Recovery la spegne.



==== Supporto per script pre-backup

Ora è possibile inserire script personalizzati nel flusso di lavoro di failover da eseguire prima di creare un backup. Gli script di pre-backup consentono di controllare lo stato della VM prima che venga replicato uno snapshot e di preparare una VM per una transizione. Ad esempio, è possibile inserire uno script che smonta un mount NFS che verrà rimontato utilizzando uno script diverso dopo il failover.

Per maggiori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html#select-vcenter-servers["Creare un piano di replica in NetApp Disaster Recovery"].



=== Resilienza al ransomware

Questa versione include miglioramenti e miglioramenti generali.



=== Cloud Volumes ONTAP



==== Supporto NVMe-TCP migliorato

In precedenza, quando si distribuivano istanze Cloud Volumes ONTAP su NVMe-TCP, era necessario ottenere e applicare manualmente le licenze NVMe prima della distribuzione. Con questo aggiornamento, Cloud Volumes ONTAP ora installa automaticamente le licenze NVMe richieste durante la distribuzione, semplificando il processo di configurazione.

Per le distribuzioni NVMe-TCP esistenti prive di licenze, Cloud Volumes ONTAP applica le licenze automaticamente. È necessario riavviare il sistema affinché le licenze abbiano effetto.

Per maggiori informazioni, vedere https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-client-protocols.html#nvme-tcp["Protocolli client supportati per Cloud Volumes ONTAP: NVMe-TCP"^] .



=== Keystone

Nuovi miglioramenti nella dashboard Keystone nella NetApp Console:



==== Completa la casella di notifica della tua copertura

La scheda *Monitoraggio avvisi* nella pagina *Monitoraggio* include una casella di notifica *Completa la copertura* che appare quando ci sono lacune nella copertura. In questa casella sono elencati gli abbonamenti per i quali mancano i monitor di capacità o scadenza e i monitor senza abbonamenti. È possibile colmare le lacune aggiungendo abbonamenti ai monitor esistenti, creando nuovi monitor o eliminando quelli non utilizzati. Per saperne di più, fare riferimento a link:https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alert-monitors.html#manage-coverage-gaps["Gestire le lacune di copertura per i monitor di allerta"].
