---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Scopri le modifiche più recenti apportate alle funzionalità e ai servizi dati che fanno parte della NetApp Console. 
---
= Modifiche recenti nella NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le modifiche più recenti apportate alle funzionalità e ai servizi dati che fanno parte della NetApp Console.  Per una cronologia completa delle versioni, vai alink:release-notes-index.html["set completo di note di rilascio"] per ogni singolo servizio.



== Servizi deprecati



=== Caching dei bordi

Il servizio di edge caching è stato rimosso il 7 agosto 2024.



=== Kubernetes

Il supporto per l'individuazione e la gestione dei cluster Kubernetes è stato rimosso il 7 agosto 2024.



=== Rapporti di migrazione

Il servizio di segnalazione delle migrazioni è stato rimosso il 7 agosto 2024.



=== Resilienza operativa

Le funzionalità di resilienza operativa sono state rimosse il 22 agosto 2025.



=== Bonifica

Il servizio di bonifica è stato rimosso il 22 aprile 2024.
