= Agente console 4.1.0
:allow-uri-read: 




=== Agente console 4.1.0

Questa versione dell'agente Console include miglioramenti della sicurezza, correzioni di bug e le seguenti funzionalità:

La versione 4.1.0 è disponibile per la modalità standard e la modalità limitata.

.Indicatori di stato dell'agente rinominati
Gli indicatori di stato per l'agente della console sono stati rinominati da *Attivo* e *Inattivo* a *Connesso* e *Disconnesso* per renderne più chiaro lo scopo.

.Supporto per Redhat Enterprise Linux (RHEL) 9.6 e Podman 5.4.0
L'agente Console ora supporta RHEL 9.6 e Podman 5.4.0. Inoltre, quando si utilizza RHEL 9 e versioni successive, NetApp supporta podman-compose 1.5.0.



=== Amministrazione NetApp Console

Questa versione include quanto segue:

.Nuovo indirizzo email per le notifiche NetApp Console
L'indirizzo email che invia le notifiche NetApp Console è cambiato da *service@console.bluexp.netapp.com* a *service@console.netapp.com*. NetApp consiglia di aggiornare tutte le regole e-mail in modo da consentire *service@console.netapp.com* per essere certi di continuare a ricevere le notifiche e-mail NetApp Console .
