= Agente console 4.3.0
:allow-uri-read: 




=== Agente console 4.3.0

La versione 4.3.0 supporta sia la modalità standard che quella limitata.

Questa versione dell'agente Console include miglioramenti della sicurezza, correzioni di bug e le seguenti funzionalità:

.Capacità di convalidare le connessioni di rete degli agenti della console
Ora è possibile convalidare le connessioni di rete degli agenti Console connessi direttamente dalla NetApp Console. Questa funzionalità aiuta a verificare la connettività e a risolvere i problemi con gli agenti Console. Questa funzionalità si aggiunge alla possibilità già esistente di eseguire la diagnostica di rete dalla riga di comando (CLI) della console di manutenzione degli agenti Console.

link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access["Scopri come eseguire la configurazione dalla NetApp Console."]



=== Amministrazione NetApp Console

Questa versione include quanto segue:

.Accesso basato sui ruoli per gruppi federati nella NetApp Console
NetApp Console supporta l'assegnazione di ruoli a gruppi federati (ad esempio, gruppi di Active Directory), consentendo agli amministratori di automatizzare l'onboarding e l'offboarding degli utenti in base all'appartenenza al gruppo nel provider di identità (IdP) dell'organizzazione. Questa funzionalità riduce il sovraccarico amministrativo e garantisce un accesso sicuro e coerente aggiornando istantaneamente l'accesso alla Console man mano che cambiano le appartenenze al gruppo.

link:https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html#add-a-federated-group-to-your-organization["Scopri come fornire l'accesso a un gruppo federato alla tua organizzazione."]

.Supporto per la federazione quando NetApp Console è in modalità limitata
Ora puoi abilitare la federazione per un'organizzazione NetApp Console in modalità limitata. Ciò consente agli utenti di accedere alla Console utilizzando le proprie credenziali aziendali, mantenendo al contempo i vantaggi di sicurezza della modalità con restrizioni.

.Modalità di sola lettura
È possibile impostare un'organizzazione NetApp Console in modalità di sola lettura. In modalità di sola lettura, gli utenti possono visualizzare risorse e impostazioni, ma non possono apportare modifiche. Un amministratore dell'organizzazione o un super amministratore può abilitare la modalità di sola lettura per un'organizzazione. Quando la modalità di sola lettura è abilitata, gli utenti con ruoli amministrativi devono elevare manualmente le proprie autorizzazioni per apportare le modifiche necessarie.

link:https://docs.netapp.com/us-en/console-setup-admin/task-enable-read-only-mode.html["Scopri come abilitare la modalità di sola lettura per un'organizzazione Console."]

link:https://docs.netapp.com/us-en/console-setup-admin/task-user-settings.html["Scopri come valorizzare il tuo ruolo quando la tua organizzazione è in modalità di sola lettura."]
