= Creazione di criteri di backup 3-2-1 durante l'attivazione del backup
:allow-uri-read: 




=== Creazione di criteri di backup 3-2-1 durante l'attivazione del backup

In precedenza, era necessario creare policy personalizzate prima di avviare uno snapshot, una replica o un backup.  Ora è possibile creare una policy durante il processo di attivazione del backup utilizzando l'interfaccia utente BlueXP backup and recovery .

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["Scopri di più sulle politiche"] .



=== Supporto per il ripristino rapido su richiesta dei volumi ONTAP

Il BlueXP backup and recovery ora offrono la possibilità di eseguire un "ripristino rapido" di un volume da un archivio cloud a un sistema Cloud Volumes ONTAP .  Il ripristino rapido è ideale per le situazioni di disaster recovery in cui è necessario fornire l'accesso a un volume il prima possibile.  Un ripristino rapido ripristina i metadati dal file di backup a un volume anziché ripristinare l'intero file di backup.

Il sistema di destinazione Cloud Volumes ONTAP deve eseguire ONTAP versione 9.13.0 o successiva. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["Scopri di più sul ripristino dei dati"] .

Il Job Monitor BlueXP backup and recovery mostra anche informazioni sullo stato di avanzamento dei processi di ripristino rapido.
