= Miglioramenti al BlueXP backup and recovery per le applicazioni (cloud-native)
:allow-uri-read: 




=== Miglioramenti al BlueXP backup and recovery per le applicazioni (cloud-native)

* Database di Microsoft SQL Server
+
** Supporta il backup, il ripristino e il recupero dei database Microsoft SQL Server residenti su Amazon FSx for NetApp ONTAP
** Tutte le operazioni sono supportate solo tramite API REST.


* Sistemi SAP HANA
+
** Durante l'aggiornamento del sistema, il montaggio e lo smontaggio automatici dei volumi vengono eseguiti utilizzando flussi di lavoro anziché script
** Supporta l'aggiunta, la rimozione, la modifica, l'eliminazione, la manutenzione e l'aggiornamento dell'host del plug-in tramite l'interfaccia utente






=== Miglioramenti al BlueXP backup and recovery per le applicazioni (ibride)

* Supporta il blocco dei dati e la protezione da ransomware
* Supporta lo spostamento dei backup da StorageGrid al livello di archiviazione
* Supporta il backup dei dati delle applicazioni MongoDB, MySQL e PostgreSQL dai sistemi ONTAP locali ad Amazon Web Services, Microsoft Azure, Google Cloud Platform e StorageGRID.  È possibile ripristinare i dati quando necessario.




=== Miglioramenti al BlueXP backup and recovery per macchine virtuali

* Supporto per il modello di distribuzione del proxy del connettore

