= È stato aggiunto il supporto per eseguire il backup dei volumi nei bucket sui sistemi ONTAP configurati con S3
:allow-uri-read: 


[IMPORTANT]
====
* Grazie a un importante miglioramento della sicurezza, il tuo Connector ora necessita di accesso Internet in uscita a un endpoint aggiuntivo per gestire le risorse di backup e ripristino all'interno del tuo ambiente cloud pubblico.  Se questo endpoint non è stato aggiunto all'elenco "consentito" nel firewall, nell'interfaccia utente verrà visualizzato un errore relativo a "Servizio non disponibile" o "Impossibile determinare lo stato del servizio":
+
\ https://netapp-cloud-account.auth0.com

* Ora è necessario un abbonamento PAYGO per il backup e il ripristino quando si utilizza il pacchetto "CVO Professional" che consente di raggruppare il backup e il ripristino Cloud Volumes ONTAP e BlueXP backup and recovery.  In passato questo non era necessario.  Non verranno addebitati costi per l'abbonamento al backup e al ripristino per i sistemi Cloud Volumes ONTAP idonei, ma è obbligatorio quando si configura il backup su nuovi volumi.


====


=== È stato aggiunto il supporto per eseguire il backup dei volumi nei bucket sui sistemi ONTAP configurati con S3

Ora è possibile utilizzare un sistema ONTAP configurato per Simple Storage Service (S3) per eseguire il backup dei volumi nell'archiviazione di oggetti.  Questa funzionalità è supportata sia per i sistemi ONTAP locali sia per i sistemi Cloud Volumes ONTAP .  Questa configurazione è supportata nelle distribuzioni cloud e nelle sedi locali senza accesso a Internet (distribuzione in modalità "privata").

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html["Saperne di più"] .



=== Ora puoi includere gli snapshot esistenti da un volume protetto nei tuoi file di backup

In passato era possibile includere copie Snapshot esistenti da volumi di lettura-scrittura nel file di backup iniziale nell'archiviazione degli oggetti (anziché iniziare con la copia Snapshot più recente).  Le copie snapshot esistenti dai volumi di sola lettura (volumi di protezione dati) non sono state incluse nel file di backup.  Ora puoi scegliere di includere le copie Snapshot più vecchie nel file di backup per i volumi "DP".

Al termine dei passaggi del backup, la procedura guidata visualizza un prompt in cui è possibile selezionare questi "Snapshot esistenti".



=== Il BlueXP backup and recovery non supportano più il backup automatico dei volumi aggiunti in futuro

In precedenza era possibile selezionare una casella nella procedura guidata di backup per applicare il criterio di backup selezionato a tutti i volumi futuri aggiunti al cluster.  Questa funzionalità è stata rimossa in seguito al feedback degli utenti e al mancato utilizzo di questa funzionalità.  Sarà necessario abilitare manualmente i backup per tutti i nuovi volumi aggiunti al cluster.



=== La pagina Monitoraggio Lavori è stata aggiornata con nuove funzionalità

La pagina Monitoraggio processi ora fornisce maggiori informazioni relative alla strategia di backup 3-2-1.  Il servizio fornisce anche notifiche di avviso aggiuntive relative alla strategia di backup.

Il filtro di tipo "Ciclo di vita del backup" è stato rinominato "Conservazione".  Utilizzare questo filtro per monitorare il ciclo di vita del backup e identificare la scadenza di tutte le copie di backup.  Il tipo di processo "Conservazione" acquisisce tutti i processi di eliminazione degli snapshot avviati su un volume protetto dal BlueXP backup and recovery.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["Scopri di più sul Job Monitor aggiornato"] .
