= Utilizzare i gruppi di sicurezza di Azure esistenti durante la creazione di un broker di dati
:allow-uri-read: 




=== Utilizzare i gruppi di sicurezza di Azure esistenti durante la creazione di un broker di dati

Ora gli utenti hanno la possibilità di utilizzare i gruppi di sicurezza di Azure esistenti durante la creazione di un broker di dati.

L'account di servizio utilizzato durante la creazione del broker di dati deve disporre delle seguenti autorizzazioni:

* "Microsoft.Network/networkSecurityGroups/securityRules/read"
* "Microsoft.Network/networkSecurityGroups/read"


https://docs.netapp.com/us-en/bluexp-copy-sync/task-installing-azure.html["Scopri di più sulla creazione di un broker di dati in Azure."]



=== Crittografa i dati durante la sincronizzazione con Google Storage

Ora gli utenti hanno la possibilità di specificare una chiave di crittografia gestita dal cliente quando creano una relazione di sincronizzazione con un bucket di Google Storage come destinazione.  Puoi inserire manualmente la tua chiave oppure sceglierla da un elenco di chiavi in una singola regione.

L'account di servizio utilizzato durante la creazione del broker di dati deve disporre delle seguenti autorizzazioni:

* cloudkms.cryptoKeys.list
* cloudkms.keyRings.list


https://docs.netapp.com/us-en/bluexp-copy-sync/reference-requirements.html#google-cloud-storage-bucket-requirements["Scopri di più sui requisiti dei bucket di Google Cloud Storage."]
